### PR TITLE
Call `toString` on message strings

### PR DESCRIPTION
**Pull request by coladarci**
I ran into a problem w/ passing translated strings (https://github.com/jamesarosen/ember-i18n) to `toastr.success`). 

The issues is that `this.i18n.t('my.translation.path')` returns a `SafeString` object (not a raw string). Passing this directly to `toastr` results in empty text, for this reason as it doesn't know what to do w/ a `SafeString`.

The simplest solution I could think of is to, instead of registering toastr directly, register a proxy of sorts and call `toString` on messages before passing them on.
## NOTE

The failing tests are also failing in master..

### CODE REVIEW

**Comment by coladarci** [comment]
The tests were failing because phatomjs isn't fond of es6 - I brought in a polyfill to take care of the method we were using..

**Comment by coladarci** [comment]
`nm` closing because I just realized I need to pass in an Object in this scenario.

**Comment by knownasilya** [comment]
Looks like the tests still fail.. Also, is this backwards compatible with what we had before?

**Comment by coladarci** [comment]
Yes, it absolutely should be! The tests that are failing are failing in
master as well - I was hoping you could update your tests or point me in
the right direction!

**Comment by knownasilya** [comment]
Released as v1.1.0

**Pull request merged**
