### PR TITLE
Inject into service and remove console.log message

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mydea** [comment]
See also #7, where I moved the implementation to a service, which makes it very easy to inject it into other services.

**Comment by ghost** [comment]
Thanks for the pointer, I like it and is probably a better way to inject toastr.

**Comment by knownasilya** [comment]
@sweco-sebhar I'll merge #7 first, then you can rebase your changes and I'll merge this too. Or if you aren't around, I'll just make the change manually before I release.

**Comment by knownasilya** [comment]
I changed my mind. I don't think injecting into a service is wise. I even think injecting into a component is no longer wise, but that will be removed in the next major release.

``` js
toast: inject.service(),

actions: {
  save() {
    // don't forget to use `get`, since injections are CPs
    this.get('toast').info('test');
  }
}
```

**Comment by ghost** [comment]
Would you mind motivating your thinking? To me it seems natural that toast notifications is a service to be injected where needed.

**Comment by knownasilya** [comment]
I meant that I changed my mind about adding the automatic injection into services. I did merge the service change, and that is in 1.3.0. You can now inject it into anything you like :+1:

**Comment by ghost** [comment]
Nevermind, I misunderstood - and agree that these injections are replaced by #7.

**Pull request closed without merging**
